name: Tests
on: [push, pull_request]
env:
  DEFAULT_COMPOSER_FLAGS: "--prefer-dist --no-interaction"
  CC_TEST_REPORTER_ID: 0edfa8221176e7eca9d698f9cacdcd33aad447698519f57dddfd8fd4eacb03eb
jobs:
  ## PHP UNIT
  phpunit:
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: myapp_test
        ports:
          - "8888:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      ## checkout the repoistory 
      - name: Checkout Repo
        uses: actions/checkout@v2

      ## Install(?) php
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, dom, imagick, intl, mbstring, mcrypt, memcached, mysql, pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, sqlite
          ini-values: date.timezone='UTC',error_reporting=E_ALL,display_errors=On
          coverage: xdebug

      ## install composer
      - name: Install dependencies
        run: composer install $DEFAULT_COMPOSER_FLAGS

      ## inject database
      - name: Setup database
        run: |
          sudo /etc/init.d/mysql start
          mysql -h 127.0.0.1 --port 8888 -u root -proot myapp_test < tests/data/sql/4.0.0.sql

      ## run unit tests
      - name: PHP Unit tests for PHP 7.2 7.3, 7.4, 8.0, 8.1
        run: vendor/bin/phpunit --verbose --configuration actions.phpunit.xml
        if: matrix.php == '8.1' || matrix.php == '8.0' || matrix.php == '7.4' || matrix.php == '7.3' || matrix.php == '7.2'

      ## unit test with coverage
      - name: PHP Unit tests for PHP 7.1
        run: vendor/bin/phpunit --verbose --coverage-clover=clover.xml --configuration actions.phpunit.xml
        if: matrix.php == '7.1'

      ## coverage
      - name: Code coverage
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter after-build -t clover
        if: matrix.php == '7.1'
        continue-on-error: true # if is fork
